/**
 * Fetches tests from backend and writes Playwright specs into runner/playwright/generated.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const API = process.env.API_ENDPOINT || "http://localhost:5000";

function normaliseFileName(name) {
  return String(name || "test")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "");
}

async function fetchTests() {
  const url = API + "/v1/tests";
  console.log("Fetching tests from", url);

  const res = await fetch(url);
  if (!res.ok) {
    throw new Error("Failed to fetch tests: status " + res.status);
  }

  const json = await res.json();
  const tests = Array.isArray(json.data) ? json.data : [];
  console.log("Fetched", tests.length, "tests");

  return tests;
}

function buildSpecSource(testDef) {
  const name = testDef.name || "Generated Test";
  const baseUrl = testDef.baseUrl || "http://localhost:5000";
  const steps = Array.isArray(testDef.steps) ? testDef.steps : [];

  const lines = [];
  lines.push("import { test, expect } from '@playwright/test';");
  lines.push("");
  lines.push("// Auto-generated by TestCraft runner from backend test definition");
  lines.push("test('" + name.replace(/'/g, "\\'") + "', async ({ page }) => {");
  lines.push("  const baseUrl = process.env.BASE_URL || '" + baseUrl.replace(/'/g, "\\'") + "';");
  lines.push("  await page.goto(baseUrl);");

  for (const step of steps) {
    if (!step || !step.type) continue;

    if (step.type === "navigate") {
      const urlPart = step.url || "/";
      lines.push("  await page.goto(baseUrl + '" + String(urlPart).replace(/'/g, "\\'") + "');");
    } else if (step.type === "click") {
      const sel = String(step.selector || "").replace(/"/g, '\\"');
      lines.push('  await page.click("' + sel + '");');
    } else if (step.type === "fill") {
      const sel = String(step.selector || "").replace(/"/g, '\\"');
      const val = String(step.value || "").replace(/"/g, '\\"');
      lines.push('  await page.fill("' + sel + '", "' + val + '");');
    } else if (step.type === "assertText") {
      const sel = String(step.selector || "").replace(/"/g, '\\"');
      const val = String(step.value || "").replace(/"/g, '\\"');
      lines.push('  await expect(page.locator("' + sel + '")).toHaveText("' + val + '");');
    } else {
      lines.push("  // TODO unsupported step type '" + String(step.type) + "'");
    }
  }

  lines.push("});");
  lines.push("");

  return lines.join("\n");
}

async function main() {
  const tests = await fetchTests();
  const outDir = path.resolve(__dirname, "../generated");
  if (!fs.existsSync(outDir)) {
    fs.mkdirSync(outDir, { recursive: true });
  }

  for (const t of tests) {
    const baseName = normaliseFileName(t.name || t.id || "test");
    const filePath = path.join(outDir, baseName + ".spec.ts");
    const source = buildSpecSource(t);
    fs.writeFileSync(filePath, source, "utf8");
    console.log("Wrote", filePath);
  }
}

main().catch((err) => {
  console.error("Error fetching tests:", err.message);
  process.exit(1);
});
