name: CI Pipeline (sanity)

on:
  push:
    branches:
      - "**"
  pull_request: {}

jobs:
  sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Echo context
        run: |
          echo "Workflow OK"
          echo "Ref = $GITHUB_REF"
          echo "SHA = $GITHUB_SHA"
